4

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,16 +1,37 @@
 name: My First Pipeline
 
+env:
+  RAMADAN_NAME: "ramadan"
+  RAMADAN_AGE: 23
+
 on:
   push:
     branches:
       - master
 
+# إعطاء الـ Token صلاحية كتابة الـ Issues
+permissions:
+  issues: write
+
 jobs:
   hello:
     runs-on: ubuntu-latest
-
     steps:
-
       - name: Print Message
         run: echo "CI/CD Working"
 
+      - name: Simulate Failure
+        run: |
+          echo "Simulating an error..."
+          exit 1
+
+      - name: Create GitHub Issue on Failure
+        if: failure()
+        run: |
+          curl -L \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://github.com{{ github.repository }}/issues \
+            -d '{"title":"Pipeline Failed: My First Pipeline","body":"The workflow failed during execution. Please check the logs.","labels":["bug"]}'
